w05/d03/cookbook_app/config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :recipes

end

w05/d03/cookbook_app/app/models/course.rb
class Course < ActiveRecord::Base
  has_many :recipes
end

w05/d03/cookbook_app/app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :course
end

w05/d03/cookbook_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

w05/d03/cookbook_app/app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all.order(:name)
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(params.require(:course).permit(:name, :instructions, :servings))
    if @course.save
      redirect_to courses_path
    else
      render :new
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    @course.update_attributes(params.require(:course).permit(:name, :instructions, :servings))
    if @course.save
      redirect_to courses_path
    else
      render :new
    end
  end

  def destroy
    @bean = Bean.find(params[:id])
    @bean.destroy
    redirect_to beans_path
  end


end

w05/d03/cookbook_app/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
   def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(params.require(:recipe).permit(:name, :instructions, :servings, :course_id))
    if @recipe.save
      redirect_to recipes_path
    else
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update_attributes(params.require(:course).permit(:name, :instructions, :servings))
    if @recipe.save
      redirect_to recipes_path
    else
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end
end

w05/d03/cookbook_app/app/helpers/application_helper.rb
module ApplicationHelper
end

w05/d03/cookbook_app/app/helpers/courses_helper.rb
module CoursesHelper
end

w05/d03/cookbook_app/app/helpers/recipes_helper.rb
module RecipesHelper
end

w05/d03/cookbook_app/app/views/recipes/edit.html.erb
<h1>Edit this recipe!</h1>

<%= form_for @recipe do |f| %>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :instructions %>
        <%= f.text_field :instructions %>
    </div>

    <div>
        <%= f.label :servings %>
        <%= f.text_field :servings %>
    </div>

    <%= f.submit "Submit these changes!" %>

<% end %>

<%= link_to "Back to the list!", courses_path %>

w05/d03/cookbook_app/app/views/recipes/index.html.erb
<h1>Recipes</h1>

<ul>
    <% @recipes.each do |recipe| %>
        <li>
            <strong><%= recipe.name %></strong>
            <%= link_to "More info", recipe_path(recipe) %>
        </li>
    <% end %>
</ul>

<%= link_to "Add a new recipe", new_recipe_path %>

w05/d03/cookbook_app/app/views/recipes/new.html.erb
<h1>Add a new Recipe!</h1>

<%= form_for @recipe do |f| %>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :instructions %>
        <%= f.text_field :instructions %>
    </div>

    <div>
        <%= f.label :servings %>
        <%= f.text_field :servings %>
    </div>

    <div>
        <%= f.label :course %>
        <%= f.collection_select :course_id, Course.all, :id, :name %>
    </div>
    <%= f.submit "Add new recipe!" %>

<% end %>

<%= link_to "Back to the list!", recipes_path %>

w05/d03/cookbook_app/app/views/recipes/show.html.erb
<h1> <%= @recipe.name %> </h1>

<p>This recipe for <%= @recipe.name %>  is created by <%= @recipe.instructions %> with just <%= @recipe.servings %> serving. </p>
<<p>The course for this recipe is <%= @recipe.course.name %></p>

<%= link_to "Delete this recipe!", recipe_path, method: :delete, data: { confirm: "Are you sure you want to delete this course?"} %>

<%= link_to "Edit this recipe!", edit_recipe_path(@recipe) %>

<%= link_to "Back to the list of recipes!", recipes_path %>