w04/d03/coffeeshop/config/routes.rb
Rails.application.routes.draw do
  resources :beans

end

w04/d03/coffeeshop/app/models/bean.rb
class Bean < ActiveRecord::Base
  validates_presence_of :name
end

w04/d03/coffeeshop/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

w04/d03/coffeeshop/app/controllers/beans_controller.rb
class BeansController < ApplicationController
  #before_action: find_bean, only: [:show, :edit, :update, :destroy]
    #run right before
  def index
  @beans = Bean.all
  end

  def show
    find_bean
  end

  def new
  @bean = Bean.new
  end

  # creating a new item in database
  def create
  @bean = Bean.new(bean_params)
    if @bean.save
     redirect_to beans_path
    else
     render :new
    end
  end


  #edit and update can alter info on item
  def edit
  find_bean
  end

  def update
    find_bean
    if @bean.update_attributes(bean_params)
      redirect_to beans_path
    else
      render :edit
    end
  end

  #to destroy from database
  def destroy
    find_bean
    @bean.destroy
    redirect_to beans_path
  end

  def bean_params
    params.require(:bean).permit(:name, :roast, :origin, :quantity)
  end

  def find_bean
    @bean = Bean.find(params[:id])
  end


end

w04/d03/coffeeshop/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
end

w04/d03/coffeeshop/app/helpers/application_helper.rb
module ApplicationHelper
end

w04/d03/coffeeshop/app/helpers/beans_helper.rb
module BeansHelper
end

w04/d03/coffeeshop/app/helpers/recipes_helper.rb
module RecipesHelper
end

w04/d03/coffeeshop/app/views/beans/edit.html.erb
<h1>Edit this bean!</h1>

<%= form_for @bean do |f| %>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :roast %>
        <%= f.text_field :roast %>
    </div>

    <div>
        <%= f.label :origin %>
        <%= f.text_field :origin %>
    </div>

    <div>
        <%= f.label :quantity %>
        <%= f.text_field :quantity %>
    </div>

    <%= f.submit "Submit these changes!" %>

<% end %>

<%= link_to "Back to the list!", beans_path %>

w04/d03/coffeeshop/app/views/beans/index.html.erb
<h1>Today's Beans</h1>

<ul>
    <% @beans.each do |bean| %>
        <li>
            <strong><%= bean.name %></strong> - <%= bean.roast %>
            <%= link_to "More info", bean_path(bean) %>
        </li>
    <% end %>
</ul>

<%= link_to "Add a new bean", new_bean_path %>

w04/d03/coffeeshop/app/views/beans/new.html.erb
<h1>Add a new bean!</h1>

<%= form_for @bean do |f| %>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :roast %>
        <%= f.text_field :roast %>
    </div>

    <div>
        <%= f.label :origin %>
        <%= f.text_field :origin %>
    </div>

    <div>
        <%= f.label :quantity %>
        <%= f.text_field :quantity %>
    </div>

    <%= f.submit "Add new bean!" %>

<% end %>

<%= link_to "Back to the list!", beans_path %>

w04/d03/coffeeshop/app/views/beans/show.html.erb
<h1> <%= @bean.name %> </h1>

<p>This coffee is a <%= @bean.roast %> roast from <%= @bean.origin %>, and we have <%= @bean.quantity %> pounds available.</p>

<%= link_to "Delete this bean!", bean_path, method: :delete, data: { confirm: "Are you sure you want to delete this bean?"} %>

<%= link_to "Edit this bean!", edit_bean_path(@bean) %>

<%= link_to "Back to the list!", beans_path %>