w05/d04/homes_for_sale/config/routes.rb
Rails.application.routes.draw do
  root 'houses#index'
  resources :houses
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new'

end

w05/d04/homes_for_sale/app/models/house.rb
class House < ActiveRecord::Base
end

w05/d04/homes_for_sale/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

w05/d04/homes_for_sale/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    private

     # Make the current_user method available to views, not just controllers!
    helper_method :current_user

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

     def authorize
      redirect_to login_path, alert: 'Not authorized - you must be logged in!' if current_user.nil?
    end
end

w05/d04/homes_for_sale/app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:index, :show]

  # GET /houses
  # GET /houses.json
  def index
    @houses = House.all
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)

    respond_to do |format|
      if @house.save
        format.html { redirect_to @house, notice: 'House was successfully created.' }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url, notice: 'House was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      params.require(:house).permit(:address, :bedrooms, :baths, :price)
    end
end

w05/d04/homes_for_sale/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in!'
    else
      flash.now.alert = 'Invalid login credentials - try again!'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end
end

w05/d04/homes_for_sale/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You have successfully signed up!"
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'new'
    end
  end

  private
    # Implement Strong Params
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

w05/d04/homes_for_sale/app/helpers/application_helper.rb
module ApplicationHelper
end

w05/d04/homes_for_sale/app/helpers/houses_helper.rb
module HousesHelper
end

w05/d04/homes_for_sale/app/helpers/sessions_helper.rb
module SessionsHelper
end

w05/d04/homes_for_sale/app/helpers/users_helper.rb
module UsersHelper
end

w05/d04/homes_for_sale/app/views/houses/_form.html.erb
<%= form_for(@house) do |f| %>
  <% if @house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% @house.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :bedrooms %><br>
    <%= f.number_field :bedrooms %>
  </div>
  <div class="field">
    <%= f.label :baths %><br>
    <%= f.text_field :baths %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

w05/d04/homes_for_sale/app/views/houses/edit.html.erb
<h1>Editing House</h1>

<%= render 'form' %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

w05/d04/homes_for_sale/app/views/houses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Houses</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Bedrooms</th>
      <th>Baths</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= house.address %></td>
        <td><%= house.bedrooms %></td>
        <td><%= house.baths %></td>
        <td><%= house.price %></td>
        <td><%= link_to 'Show', house %></td>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New House', new_house_path %>

w05/d04/homes_for_sale/app/views/houses/new.html.erb
<h1>New House</h1>

<%= render 'form' %>

<%= link_to 'Back', houses_path %>

w05/d04/homes_for_sale/app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @house.address %>
</p>

<p>
  <strong>Bedrooms:</strong>
  <%= @house.bedrooms %>
</p>

<p>
  <strong>Baths:</strong>
  <%= @house.baths %>
</p>

<p>
  <strong>Price:</strong>
  <%= @house.price %>
</p>

<%= link_to 'Edit', edit_house_path(@house) %> |
<%= link_to 'Back', houses_path %>

w05/d04/homes_for_sale/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HomesForSale</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p>
  <% if current_user %>
    Welcome, <%= current_user.name %>
      |
    <%= link_to 'Logout', session_path('dummy'), method: :delete %>
  <% else %>
    <%= link_to 'Login', login_path %>
      |
    <%= link_to 'Sign Up', new_user_path %>
  <% end %>
</p>

<%= yield %>

</body>
</html>